"""Tests for structure format normalisation.

Fixtures are real outputs from this pipeline, not files generated by the same
library that converts them: a Protenix mmCIF, a BoltzGen mmCIF and a Boltz PDB,
all pulled from S3. Round-tripping a file through gemmi and then asserting
gemmi reads it back would prove nothing about whether the other tools can.

The behaviour that matters most is `resolve_chain`. Converting mmCIF down to
PDB can rename chains, and every tool here takes a chain argument, so a silent
rename means designing a different chain than the caller asked for.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tools.common import convert
from fixtures import BOLTZ_PDB, BOLTZGEN_CIF, PROTENIX_CIF


class TestDetectFormat:
    @pytest.mark.parametrize("name", ["x.pdb", "x.ent", "X.PDB", "a/b/c.pdb"])
    def test_recognises_pdb(self, name):
        assert convert.detect_format(name) == "pdb"

    @pytest.mark.parametrize("name", ["x.cif", "x.mmcif", "X.CIF"])
    def test_recognises_cif(self, name):
        assert convert.detect_format(name) == "cif"

    @pytest.mark.parametrize("name", ["x.txt", "x.fa", "x", "x.npz", "x.pdb.gz"])
    def test_rejects_anything_else(self, name):
        with pytest.raises(ValueError, match="Cannot tell the structure format"):
            convert.detect_format(name)

    def test_accepts_a_path_object(self):
        assert convert.detect_format(PROTENIX_CIF) == "cif"


class TestEnsureFormatNoOp:
    def test_matching_format_returns_the_original_path(self, tmp_path):
        result = convert.ensure_format(BOLTZ_PDB, "pdb", tmp_path)
        assert result.path == BOLTZ_PDB
        assert result.converted is False

    def test_matching_format_writes_nothing(self, tmp_path):
        convert.ensure_format(BOLTZ_PDB, "pdb", tmp_path)
        assert list(tmp_path.iterdir()) == []

    def test_rejects_an_unknown_target_format(self, tmp_path):
        with pytest.raises(ValueError, match="required"):
            convert.ensure_format(BOLTZ_PDB, "mol2", tmp_path)


class TestConvertRealOutputs:
    """The case that is broken today: newer generators feeding older designers."""

    def test_protenix_cif_becomes_pdb(self, tmp_path):
        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        assert result.converted is True
        assert result.source_format == "cif"
        assert result.path.suffix == ".pdb"
        assert result.path.is_file()

    def test_boltzgen_cif_becomes_pdb(self, tmp_path):
        result = convert.ensure_format(BOLTZGEN_CIF, "pdb", tmp_path)
        assert result.converted is True
        assert result.path.is_file()

    def test_conversion_preserves_the_chains(self, tmp_path):
        before = convert.read_chain_names(PROTENIX_CIF)
        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        assert result.chains == before

    def test_conversion_preserves_residue_counts(self, tmp_path):
        """A dropped chain or truncated residue would be silent otherwise."""
        from tools.common import structure

        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        residues = structure.read_pdb(result.path)
        counts = {c: len(r) for c, r in structure.chains(residues).items()}
        assert counts == {"A": 68, "B": 68}

    def test_the_converted_file_is_readable_by_the_plain_pdb_reader(self, tmp_path):
        """ProteinMPNN and ThermoMPNN parse PDB text directly, not via gemmi."""
        from tools.common import structure

        result = convert.ensure_format(BOLTZGEN_CIF, "pdb", tmp_path)
        residues = structure.read_pdb(result.path)
        assert residues
        assert {r.chain for r in residues} == {"A", "B"}

    def test_pdb_to_cif_also_works(self, tmp_path):
        result = convert.ensure_format(BOLTZ_PDB, "cif", tmp_path)
        assert result.converted is True
        assert result.path.suffix == ".cif"
        assert result.chains == ["A", "B"]

    def test_output_lands_in_the_given_directory(self, tmp_path):
        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        assert result.path.parent == tmp_path

    def test_does_not_overwrite_its_own_input(self, tmp_path):
        """Guards the case where converting would collide with the source name."""
        source = tmp_path / "model.cif"
        source.write_bytes(PROTENIX_CIF.read_bytes())
        result = convert.ensure_format(source, "pdb", tmp_path)
        assert result.path != source
        assert source.is_file()


class TestResolveChain:
    def test_passes_a_chain_through_when_nothing_was_renamed(self, tmp_path):
        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        assert result.renamed_chains == {}
        assert convert.resolve_chain("B", result) == "B"

    def test_translates_a_renamed_chain(self):
        converted = convert.Converted(
            path=Path("x.pdb"), format="pdb", converted=True,
            renamed_chains={"polymer_1": "A", "polymer_2": "B"},
        )
        assert convert.resolve_chain("polymer_2", converted) == "B"

    def test_leaves_unrenamed_chains_alone_in_a_partial_rename(self):
        converted = convert.Converted(
            path=Path("x.pdb"), format="pdb", converted=True,
            renamed_chains={"LONG": "A"},
        )
        assert convert.resolve_chain("B", converted) == "B"

    def test_translates_a_space_separated_list(self):
        converted = convert.Converted(
            path=Path("x.pdb"), format="pdb", converted=True,
            renamed_chains={"LONG": "A"},
        )
        assert convert.resolve_chains("LONG B", converted) == "A B"

    def test_a_list_survives_when_nothing_was_renamed(self, tmp_path):
        result = convert.ensure_format(PROTENIX_CIF, "pdb", tmp_path)
        assert convert.resolve_chains("A B", result) == "A B"
